from . import sales_team
from . import hr_employee
from . import sale
from . import quotation
from . import blanket_orders
from . import account_move
from . import credit_limit
from . import employee_sale_team_history
from . import res_partner
from . import sale_targets
from . import temp_credit_request
from . import stock_picking
from . import multi_scrap
from . import mrp_mr
from . import customer_return_request
from . import inventory
from . import crm_claim_ept
from . import repair