from . import res_users
from . import stock_location
from . import stock_warehouse
from . import stock_picking
from . import stock_quant
from . import product
from . import stock_orderpoint
from . import stock_inventory
from . import product_strategy