# -*- coding: utf-8 -*-
{
    'name': 'Basic Solution - Finance Dimension For SPE',
    'version': '14.2.0.0',
    'summary': """10 Finance Dimensions For Sale,Purchase,Account,Inventory """,
    'author': "Basic Solution Co., Ltd.",
    'website': "https://www.basic-solution.com",
    'category': 'Accounting/Accounting',
    'depends': ['base', 'bs_finance_dimension', 'is_customer_is_vendor','hr','sales_team'],
    "data": [
        "data/dimension_group_data.xml",
        "views/bs_dimension_group_views.xml",
        "views/purchase_order_views.xml",
        "views/sale_order_views.xml",
        "views/account_move_views.xml",
        "views/stock_picking_views.xml",
        "views/account_account_views.xml",
        "views/hr_expense_views.xml",
        "views/stock_valuation_layer_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    'uninstall_hook': 'uninstall_hook',
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
